cache:
  paths:
    - node_modules

stages:
  - test
  - build

test:lint:
  stage: test
  image: node:8
  before_script:
    - npm install
  script:
    - npm test

build:python:
  stage: build
  image: python:3.6
  script:
    - bin/download.py
