matrix:
  include:
    - language: python
      python: "3.6"
      script:
        - "./bin/download.py"
    - language: node_js
      node_js: "8"
      cache:
        directories:
          - node_modules
