COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 8"
  - "ios >= 7"

PATHS:
  dist: "dist"
  data: "src/data/**/*"
  images:
    - "src/assets/img/**/*"
  javascript:
    src: "src/assets/js/**/*.js"
    entry: "src/assets/js/main.js"
  sass:
    src: "src/assets/scss/**/*.scss"
    entry: "src/assets/scss/main.scss"
    modules:
      - "node_modules/reset-css"
      - "node_modules/spinkit/scss"
  pages: "src/**/*.html"

SERVER:
  port: 8000
